server:
    port: 8080
    servlet:
        context-path: /v1

spring:
    datasource:
        url: jdbc:postgresql://localhost:5432/modding
        username: admin
        password: admin
        driver-class-name: org.postgresql.Driver

    jpa:
        hibernate:
            ddl-auto: update
        open-in-view: false
        properties:
            "[hibernate.jdbc.time_zone]": UTC

    config:
        import: optional:file:.env[.properties]

logging:
    level:
        root: INFO
        "[org.springframework.security]": DEBUG
        "[org.hibernate.SQL]": DEBUG
        

app:
  jwt:
    issuer: "mp01-api"
    audience: "mp01-clients"
    access-mins: 15
    refresh-days: 15
    secret-b64: "${JWT_SECRET_B64:CHANGE_ME_BASE64_32B+}"